services:
  web:
    build:
      context: .
      target: prod
    env_file:
      - .env
    volumes:
      - media:/app/media
      - private_media:/app/private_media
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: always

  celery:
    build:
      context: .
      target: prod
    command: celery -A config worker -l INFO
    env_file:
      - .env
    volumes:
      - media:/app/media
      - private_media:/app/private_media
    depends_on:
      - redis
      - rabbitmq
    restart: always

  celery-beat:
    build:
      context: .
      target: prod
    command: celery -A config beat -l INFO
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    restart: always

  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    restart: always

  rabbitmq:
    image: rabbitmq:3
    restart: always

volumes:
  pgdata:
  media:
  private_media:
