# Generated by Django 6.0 on 2026-01-09 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="tracker_use_phone_n_826f19_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="tracker_use_is_acti_83800d_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Номер телефона должен начинаться с 7 и содержать 11 цифр. Пример: 79051234567",
                        regex="^7\\d{10}$",
                    )
                ],
            ),
        ),
    ]
