# Generated by Django 6.0.1 on 2026-01-12 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_remove_user_tracker_use_phone_n_826f19_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите кличку питомца",
                        max_length=100,
                        verbose_name="Кличка",
                    ),
                ),
                (
                    "pet_type",
                    models.CharField(
                        choices=[("cat", "Кошка"), ("dog", "Собака")],
                        max_length=10,
                        verbose_name="Вид животного",
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        help_text="Например: сиамская, дворняга и т.д.",
                        max_length=100,
                        verbose_name="Порода",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Вес в килограммах",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Возраст в полных годах", verbose_name="Возраст"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Чёрный"),
                            ("white", "Белый"),
                            ("brown", "Коричневый"),
                            ("gray", "Серый"),
                            ("ginger", "Рыжий"),
                            ("cream", "Кремовый"),
                            ("multicolored", "Разноцветный"),
                        ],
                        max_length=50,
                        verbose_name="Окрас",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото питомца",
                        null=True,
                        upload_to="pets/%Y/%m/%d/",
                        verbose_name="Фотография",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хозяин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Питомец",
                "verbose_name_plural": "Питомцы",
                "ordering": ["-created_at"],
            },
        ),
    ]
