# Generated by Django 6.0.1 on 2026-01-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="age",
        ),
        migrations.AddField(
            model_name="pet",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
