# Generated by Django 6.0.1 on 2026-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_pet_age_pet_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="color",
            field=models.CharField(max_length=50, verbose_name="Окрас"),
        ),
    ]
