# Generated by Django 6.0.1 on 2026-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_pet_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="has_castration",
            field=models.BooleanField(default=False),
        ),
    ]
