# Generated by Django 6.0.1 on 2026-02-03 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_pet_gender_pet_has_castration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото питомца",
                null=True,
                upload_to="pets/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic", "heif"]
                    )
                ],
                verbose_name="Фотография",
            ),
        ),
    ]
