# Generated by Django 6.0.1 on 2026-02-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_recurrencerule_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurrence_date", models.DateField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.event"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "occurrence_date")},
            },
        ),
    ]
