# Generated by Cursor on 2026-02-24

from django.db import migrations, models


def forwards_copy_timezone_to_offset(apps, schema_editor):
    Event = apps.get_model("tracker", "Event")
    for event in Event.objects.all().only("id", "timezone"):
        try:
            offset = int(event.timezone)
        except Exception:
            offset = 0
        Event.objects.filter(id=event.id).update(timezone_offset=offset)


def backwards_copy_offset_to_timezone(apps, schema_editor):
    Event = apps.get_model("tracker", "Event")
    for event in Event.objects.all().only("id", "timezone_offset"):
        Event.objects.filter(id=event.id).update(timezone=str(event.timezone_offset))


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0011_eventnotificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone_offset",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            forwards_copy_timezone_to_offset,
            backwards_copy_offset_to_timezone,
        ),
        migrations.RemoveField(
            model_name="event",
            name="timezone",
        ),
    ]

