# Generated by Django 6.0.1 on 2026-02-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_event_timezone_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("deworming", "Deworming"),
                    ("yearlyVaccination", "Yearly vaccination"),
                    ("rabiesVaccination", "Rabies vaccination"),
                    ("weeklyPills", "Weekly pills"),
                    ("dailyPills", "Daily pills"),
                    ("grooming", "Grooming"),
                    ("bathing", "Bathing"),
                    ("walking", "Walking"),
                    ("feeding", "Feeding"),
                    ("nailTrimming", "Nail trimming"),
                    ("fleaTreatment", "Flea treatment"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="EventCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurrence_date", models.DateField()),
                ("done_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.event"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "occurrence_date")},
            },
        ),
    ]
