# Generated by Django 6.0.1 on 2026-03-16 06:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_event_done_event_type_eventcompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Вес в килограммах",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Вес (кг)",
            ),
        ),
    ]
