# Generated by Django 6.0.1 on 2026-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_alter_event_time_alter_pet_weight"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventnotificationlog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="eventnotificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("reminder", "Reminder (day before)"),
                    ("final", "Final (day of)"),
                ],
                default="standard",
                max_length=16,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventnotificationlog",
            unique_together={("event", "occurrence_date", "notification_type")},
        ),
    ]
