# Generated by Django 6.0.1 on 2026-10-02 20:53

"""Несколько времён в день: ``RecurrenceRule.times``, ``occurrence_time`` у отметок и журнала
уведомлений; уникальность с ``nulls_distinct=False`` (``NULL`` ведёт себя как раньше).
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0019_recurrence_yearly_end_count"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventcompletion",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="eventnotificationlog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="eventcompletion",
            name="occurrence_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventnotificationlog",
            name="occurrence_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recurrencerule",
            name="times",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="eventcompletion",
            constraint=models.UniqueConstraint(
                fields=("event", "occurrence_date", "occurrence_time"),
                name="uniq_completion_slot",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="eventnotificationlog",
            constraint=models.UniqueConstraint(
                fields=(
                    "event",
                    "occurrence_date",
                    "occurrence_time",
                    "notification_type",
                ),
                name="uniq_notification_slot",
                nulls_distinct=False,
            ),
        ),
    ]
