# Generated by Django 6.1.1 on 2026-10-03 08:59

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_recurrence_times_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=tracker.models.user_avatar_path, verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя'),
        ),
    ]
