# Generated by Django 6.1.1 on 2026-10-03 09:01

import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_user_profile_name_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('problem', 'Проблема'), ('idea', 'Идея'), ('question', 'Вопрос')], max_length=20)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=tracker.models.feedback_screenshot_path)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('build_number', models.CharField(blank=True, max_length=32)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
    ]
