# Generated by Django 6.1.1 on 2026-10-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('deworming', 'Deworming'), ('yearlyVaccination', 'Yearly vaccination'), ('rabiesVaccination', 'Rabies vaccination'), ('weeklyPills', 'Weekly pills'), ('dailyPills', 'Daily pills'), ('grooming', 'Grooming'), ('bathing', 'Bathing'), ('walking', 'Walking'), ('feeding', 'Feeding'), ('nailTrimming', 'Nail trimming'), ('fleaTreatment', 'Flea treatment'), ('vetVisit', 'Vet visit'), ('custom', 'Custom')], default='custom', max_length=32),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_categories', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
