# Generated by Django 6.0.1 on 2026-10-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0023_notification_settings_vet_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmdevice",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[("ios", "iOS"), ("android", "Android")],
                default="",
                max_length=10,
            ),
        ),
    ]
