# Generated by Django 6.0.1 on 2026-10-04 16:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0024_fcmdevice_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("event", "Напоминание о событии"),
                            ("announcement", "Объявление"),
                        ],
                        default="event",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("deworming", "Deworming"),
                            ("yearlyVaccination", "Yearly vaccination"),
                            ("rabiesVaccination", "Rabies vaccination"),
                            ("weeklyPills", "Weekly pills"),
                            ("dailyPills", "Daily pills"),
                            ("grooming", "Grooming"),
                            ("bathing", "Bathing"),
                            ("walking", "Walking"),
                            ("feeding", "Feeding"),
                            ("nailTrimming", "Nail trimming"),
                            ("fleaTreatment", "Flea treatment"),
                            ("vetVisit", "Vet visit"),
                            ("custom", "Custom"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("standard", "Standard"),
                            ("reminder", "Reminder (day before)"),
                            ("final", "Final (day of)"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("occurrence_date", models.DateField(blank=True, null=True)),
                ("occurrence_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tracker.event",
                    ),
                ),
                (
                    "log",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="tracker.eventnotificationlog",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tracker.pet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at", "-id"],
                        name="notif_user_created_idx",
                    ),
                    models.Index(
                        condition=models.Q(("read_at__isnull", True)),
                        fields=["user"],
                        name="notif_user_unread_idx",
                    ),
                ],
            },
        ),
    ]
